name: nourhan_portfolio
description: Nourhan Ayman — Flutter Developer Portfolio
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_bloc: ^8.1.6

  # DI
  get_it: ^8.0.2

  # Navigation
  go_router: ^14.2.7

  # UI
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  visibility_detector: ^0.4.0+2
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  bloc_test: ^9.1.7

flutter:
  uses-material-design: true
