name: nourhan_portfolio
description: Nourhan Ayman — Flutter Developer Portfolio
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_bloc: ^9.1.1

  # DI
  get_it: ^9.2.1

  # Navigation
  go_router: ^17.2.1

  # UI
  google_fonts: ^8.0.2
  visibility_detector: ^0.4.0+2
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  bloc_test: ^10.0.0

flutter:
  uses-material-design: true
